apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mycluster
  region: us-east-1

managedNodeGroups:
  - name: spot
    instanceType: m5.large
    desiredCapacity: 10
    spot: true
 

#eksctl create cluster -f cluster.yaml
#eksctl create cluster --config-file=cluster.yaml