apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mycluster
  region: us-east-1

managedNodeGroups:
  - name: spot
    instanceType: m5.large
    desiredCapacity: 3
    spot: true
    ssh:
      publicKeyName: hipstershop
 

#eksctl create cluster -f cluster.yaml
#eksctl create cluster --config-file=eks-cluster.yaml
# eksctl delete cluster --config-file=eks-cluster.yaml
# 'eksctl delete cluster --region=us-east-1 --name=myekscluster01'